all: clean probs

probs:
		javac ./prob1/prob1a/*.java
		javac ./prob2/prob2a/*.java
		javac ./prob2/prob2b/*.java
		javac ./prob3/*.java
clean:
		rm -f ./prob1/prob1a/*.class
		rm -f ./prob2/prob2a/*.class
		rm -f ./prob2/prob2b/*.class
		rm -f ./prob3/*.class
